### ISSUE TITLE
Regisztrációs Űrlap

### ISSUE THREAD

**Issue by fulopmartin21** [fulopmartin21/HaladoSzoftTech#6]
Frontend:

Készítsd el a regisztrációs űrlapot, hogy a user-ek tudjanak regisztrálni az oldalunkra.
A regisztrációhoz szükséges űrlapnak tartalmaznia kell az adatbázis alapján a következő mezőket:

1. Név (szöveges,kötelező mező) 
2. Születési hely (szöveges,kötelező mező)
3. Születési idő (szöveges,kötelező mező)
4. Jelszó (jelszó,titkosítva,kötelező mező)
5. Jelszó megint (jelszó,titkosítva,kötelező mező)
6. Felhasználónév (szöveges,kötelező mező,unique) 

Legyen egy Főoldal, ahol a Regisztráció gombra kattintva irányít át erre az oldalra.
Ha a feltöltés sikeres volt, irányítsuk át a bejelentkező felületre, és tájékoztassuk, hogy most már be tud jelentkezni.

---

Backend:

A regisztrációkor az alábbi adatokat adjuk meg:
1. Név (szöveges,kötelező mező) 
2. Születési hely (szöveges,kötelező mező)
3. Születési idő (szöveges,kötelező mező)
4. Jelszó (jelszó,titkosítva,kötelező mező)
5. Jelszó megint (jelszó,titkosítva,kötelező mező)
6. Felhasználónév (szöveges,kötelező mező,unique) 

Ha minden kötelező mezőt kitöltött a user, nézzük meg, hogy van-e már ilyen felhasználónévvel regisztrálva az oldalunkra, ha igen, akkor ne engedjük a regisztrációt és írjuk ki a felhasználónak a képernyőre, hogy már történt regisztráció ezzel a felhasználónévvel, ha pedig nincsen még ilyen felhasználónév, akkor töltsük fel az adatait az adatbázisba.
Ha valami miatt meghiúsul a regisztráció, akkor maradjunk a regisztrációs oldalon, és felugró ablakban tájékoztassuk,
hogy milyen hiba végett nem sikerült regisztrálnia. A hibát természetesen naplózzuk.

Update:
A username karakterhossza minimum 5 karakter kell legyen, és nem tartalmazhat space-t vagy blank-et. Az engedélyezett karakterek:
- kisbetű
- nagybetű
- szám

A jelszónak legalább 8 karakternek kell lennie, és a következőket tartalmazhatja:
- kisbetű
- nagybetű
- szám
Amennyiben a username nem unique vagy nem megfelelő a karakterek száma/összetétele, úgy tájékoztassuk a felhasználót, hogy az általa választott felhasználónév formátuma nem megfelelő, és írjuk ki, hogy hogyan épülhet fel.
Amennyiben a jelszó nem megfelelő formátumú, tájékoztassuk a felhasználót, hogy az általa választott jelszó nem megfelelő, és írjuk ki, hogy a jelszó hogyan épülhet fel.
Ha a felhasználó által választott jelszó nem egyezik meg a 2 mezőben, tájékoztassuk, hogy a két begépelt jelszó nem egyezik.

**Comment by atomrom** [comment]
Nincs szo az edge case-ekrol. Pl. ez egy valid jelszo? -> "". Es ez? "   ". Stb. Mi van, ha valami invalid?

A username egyedi. Oke. Es ha mar olyat akarnak megadni, amit mar hasznalnak?
Az ures string valud username? A space? 1 db tab? Van minimalis hossz?
